---

- name: Install process-exporter for ubuntu
  hosts: ntpservers
  vars:
    - deb_source: https://github.com/ncabatoff/process-exporter/releases/download/v0.7.10/process-exporter_0.7.10_linux_amd64.deb
    - deb: process-exporter_0.7.10_linux_amd64.deb
    - file: https://github.com/rnenergy/chrony_server/blob/main/all.yaml
  become: yes
  
  tasks:
  - name: update packages
    apt:
     update_cache: yes
  
  - name: wget process-exporter deb
    shell: wget {{deb_source}}
  
  - name: dpkg process-exporter deb and make dir for it
    shell: dpkg -i {{deb}} && mkdir -p /etc/process-exporter/
    
  - name: Make dir for process-exporter
    shell: mkdir -p /etc/process-exporter/
    
  - name: Download all.yaml file
    shell: cd /etc/process-explorer && wget {{file}} 
      
    
  - name: Enable and start process exporter
    shell: systemctl enable process-exporter && systemctl start process-exporter
            
  - name: Process-exporter status
    shell: systemctl status process-exporter
      
  - name: Print all available facts
    debug:
      var: ansible_facts